server:
  port: 8085

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    reactor.netty: INFO

spring:
  cloud:
    gateway:
      routes:
        # -------- PATIENT-SERVICE (Mongo @ 8080) --------
        - id: patient-create
          uri: http://${PATIENT_SERVICE_BASEURL:localhost:8080}
          predicates:
            - Path=/patients
            - Method=POST
          filters:
            - SetPath=/api/patient

        - id: patient-get-by-nationalid
          uri: http://${PATIENT_SERVICE_BASEURL:localhost:8080}
          predicates:
            - Path=/patients
            - Method=GET
          filters:
            # Pass-through query param nationalId automatically
            - SetPath=/api/patient

        - id: patient-all
          uri: http://${PATIENT_SERVICE_BASEURL:localhost:8080}
          predicates:
            - Path=/patients/all
            - Method=GET
          filters:
            - SetPath=/api/patient/all

        # -------- DOCTOR-SERVICE (MySQL @ 8083) --------
        - id: doctor-routes
          uri: http://${DOCTOR_SERVICE_BASEURL:localhost:8083}
          predicates:
            - Path=/doctors/**
            - Method=GET
          filters:
            # /doctors/1 -> /api/doctor/1
            # /doctors/1/timeslots -> /api/doctor/1/timeslots
            - RewritePath=/doctors/(?<segment>.*), /api/doctor/${segment}

        - id: timeslot-reserve
          uri: http://${DOCTOR_SERVICE_BASEURL:localhost:8083}
          predicates:
            - Path=/timeslots/reserve
            - Method=POST
          filters:
            - SetPath=/api/timeslot/reserve

        # -------- APPOINTMENT-SERVICE (MySQL @ 8084) --------
        - id: appointments-create
          uri: http://${APPOINTMENT_SERVICE_BASEURL:localhost:8084}
          predicates:
            - Path=/appointments
            - Method=POST
          filters:
            - SetPath=/api/appointment

        - id: appointments-list
          uri: http://${APPOINTMENT_SERVICE_BASEURL:localhost:8084}
          predicates:
            - Path=/appointments
            - Method=GET
          filters:
            - SetPath=/api/appointment
